const lp=(p,l)=>l==="en"?(p==="/"?"/en/":"/en"+p):p;
const css=`
.bioa-hub{padding-top:70px!important}.bioa-hub__intro{max-width:900px;margin-bottom:34px}.bioa-hub__intro h2{margin:0 0 12px;font-size:clamp(36px,4vw,64px);line-height:1.04;font-weight:400}.bioa-hub__intro p{max-width:760px;font-size:18px;line-height:1.55;color:#59645d}.bioa-hub__grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.bioa-hub__card{position:relative;min-height:270px;padding:34px;border-radius:38px;overflow:hidden;background:linear-gradient(135deg,#F8FAF5 0%,#E7F0E8 100%);border:1px solid rgba(17,111,71,.08);text-decoration:none;color:#052F21}.bioa-hub__card:nth-child(even){background:linear-gradient(135deg,#FCFEF1,#F3F0E4)}.bioa-hub__card:after{content:"";position:absolute;right:-44px;bottom:-54px;width:230px;height:280px;background:#116F47;opacity:.055;-webkit-mask:url("/assets/bioa-monogram.svg") center/contain no-repeat;mask:url("/assets/bioa-monogram.svg") center/contain no-repeat}.bioa-hub__kicker{font-size:13px;text-transform:uppercase;letter-spacing:.08em;color:#116F47;margin-bottom:12px}.bioa-hub__card h3{position:relative;z-index:1;margin:0 0 12px;font-size:30px;font-weight:450}.bioa-hub__card p{position:relative;z-index:1;max-width:75%;margin:0;color:#59645d;line-height:1.5}.bioa-hub__services{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin-top:50px}.bioa-hub__service{padding:28px;border-radius:28px;background:#fff;border:1px solid rgba(17,111,71,.08)}.bioa-hub__service h3{font-size:22px;font-weight:500;margin:0 0 8px}.bioa-hub__service p{color:#647067;margin:0 0 16px;line-height:1.45}.bioa-hub__service a{color:#116F47;font-weight:600;text-decoration:none}@media(max-width:768px){.bioa-hub__grid,.bioa-hub__services{grid-template-columns:1fr}.bioa-hub__card{min-height:230px;padding:28px;border-radius:28px}.bioa-hub__card p{max-width:88%}}
`;
export function applyHubV4($,route,lang){
  if(route!=="/contract-manufacturing-cosmetics/")return;
  $("head").append('<style id="bioa-hub-v4">'+css+'</style>');$(".bioa-hub").remove();
  const vi=lang==="vi";
  const cards=vi?[["cham-soc-da","Chăm sóc da","Serum, toner, kem dưỡng, mặt nạ và các sản phẩm chăm sóc da theo định vị thương hiệu."],["lam-sach","Làm sạch","Sữa rửa mặt, tẩy trang, tẩy tế bào chết và các giải pháp làm sạch dịu nhẹ."],["cham-soc-co-the","Chăm sóc cơ thể","Sữa tắm, lotion, kem body, sản phẩm khử mùi và chăm sóc cơ thể."],["cham-soc-toc","Tóc & da đầu","Dầu gội, dầu xả, serum tóc và sản phẩm chăm sóc da đầu."],["serum","Serum & tinh chất","Dòng tinh chất cô đặc phát triển theo công dụng và nhóm hoạt chất mục tiêu."],["spa","Spa & chuyên nghiệp","Gel, kem massage và sản phẩm sử dụng tại spa, clinic hoặc khách sạn."]]:[["cham-soc-da","Skincare","Serums, toners, creams, masks and skincare products aligned with your brand positioning."],["lam-sach","Cleansing","Facial cleansers, makeup removers, exfoliants and gentle cleansing solutions."],["cham-soc-co-the","Body care","Body wash, lotions, body creams, deodorants and daily body care."],["cham-soc-toc","Hair & scalp","Shampoo, conditioner, hair serum and scalp-care products."],["serum","Serums & concentrates","Concentrated formulas built around target benefits and active ingredients."],["spa","Spa & professional","Massage gels, creams and products for spas, clinics and hotels."]];
  const services=vi?[["Gia công trọn gói OEM/ODM","Từ ý tưởng, R&D công thức, mẫu thử đến sản xuất và hoàn thiện thành phẩm.","/contract-manufacturing-cosmetics/"],["Công thức có sẵn","Rút ngắn thời gian triển khai với các công thức nền có thể điều chỉnh theo định vị.","/white-label-cosmetics/"],["Công thức độc quyền","Phát triển công thức riêng theo mục tiêu sản phẩm và chiến lược thương hiệu.","/private-label-cosmetics/"]]:[["Full-service OEM/ODM","From concept and formulation to samples, production and finished goods.","/contract-manufacturing-cosmetics/"],["Ready formulas","Shorten launch time with proven base formulas adapted to your positioning.","/white-label-cosmetics/"],["Custom formulas","Develop exclusive formulas around your product goals and brand strategy.","/private-label-cosmetics/"]];
  const html='<section class="block bioa-hub"><div class="container"><div class="bioa-hub__intro"><div class="label">'+(vi?'GIA CÔNG MỸ PHẨM':'COSMETIC MANUFACTURING')+'</div><h2>'+(vi?'Danh mục gia công mỹ phẩm':'Cosmetic Manufacturing Categories')+'</h2><p>'+(vi?'Mẫu danh mục được xây dựng dựa trên nhóm dịch vụ và định hướng sản xuất của website BIO-A cũ, giữ ngôn ngữ bố cục Merywood để bạn tiếp tục duyệt và tinh chỉnh.':"A sample category hub based on BIO-A's existing manufacturing direction while keeping the Merywood layout language.")+'</p></div><div class="bioa-hub__grid">'+cards.map(c=>'<a class="bioa-hub__card" id="'+c[0]+'" href="'+lp("/contacts/",lang)+'"><div class="bioa-hub__kicker">BIO-A Group</div><h3>'+c[1]+'</h3><p>'+c[2]+'</p></a>').join("")+'</div><div class="bioa-hub__services">'+services.map(s=>'<div class="bioa-hub__service"><h3>'+s[0]+'</h3><p>'+s[1]+'</p><a href="'+lp(s[2],lang)+'">'+(vi?'Xem giải pháp →':'Explore →')+'</a></div>').join("")+'</div></div></section>';
  const hero=$("main .block").first();if(hero.length)hero.after(html);else $("main").prepend(html);
}